services:
  db:
    container_name: tidytodo-database
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - tidytodo-mysqldata:/var/lib/mysql
    environment:
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
  app:
    container_name: tidytodo-server
    build: .
    ports:
      - 3001:3000
  
volumes:
  tidytodo-mysqldata:
